version: "2"

run:
  timeout: 5m

linters:
  disable:
    - dupl
  settings:
    errorlint:
      errorf: true
      
    gosec:
      excludes:
        - G402 # Look for bad TLS connection settings
        - G306 # Poor file permissions used when writing to a new file
        - G601 # Implicit memory aliasing in for loop
        - G115 # Integer overflow in conversion

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - funlen
          - revive

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true