project_name: lndnotify
version: 2

# Disable release creation for snapshot builds
release:
  disable: true

builds:
  - 
    env:
      - CGO_ENABLED=0
    binary: lndnotify
    ldflags:
      - -s -w -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

upx:
  -
    enabled: true
    goos:
      - linux
    compress: best
    lzma: true

dockers:
  - image_templates:
    - "ghcr.io/primexz/lndnotify:dev-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
    - "--platform=linux/amd64"

  - image_templates:
    - "ghcr.io/primexz/lndnotify:dev-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
    - "--platform=linux/arm64/v8"

docker_manifests:
  - name_template: "ghcr.io/primexz/lndnotify:dev"
    image_templates:
    - "ghcr.io/primexz/lndnotify:dev-amd64"
    - "ghcr.io/primexz/lndnotify:dev-arm64v8"